### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by LeMeteore** [knibals/dotfiles#1]
Allez, tu fork mon dotfiles et oublies pas de me mettre une etoile :)

**Comment by knibals** [comment]
C'est vrai qu'il te manque un `vimrc`. Mais je ne comprends pas la moitié de tes `bashrc`.

**Comment by LeMeteore** [comment]
Je maintiens un bashrc minimal, de base, et tous les autres bashrc_\* sont appelés a partir du premier. Lis calmement, tu comprendras.
